services:
  nginx:
    image: nginx:latest
    container_name: nginx-full-cycle-rocks
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app

  node-app:
    build: ./node-app
    container_name: node-app-full-cycle-rocks
    volumes:
      - ./node-app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=people_db
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    command: >
          dockerize -wait tcp://mysql:3306 -timeout 60s npm start

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-full-cycle-rocks
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: people_db
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
